use_frameworks!

target 'BzbsXDtacSDK_Example' do
  pod 'BzbsXDtacSDK', :path => '../'
  pod 'AppCenter'
  pod 'AppCenter/Crashes'
  pod 'AppCenter/Analytics'
  
  pod 'Firebase/Analytics'
#  pod 'Firebase/Performance'

  target 'BzbsXDtacSDK_Tests' do
    inherit! :search_paths

    pod 'Quick'#, '~> 1.2.0'
    pod 'Nimble'#, '~> 7.0'
    pod 'FBSnapshotTestCase'# , '~> 2.1.4'
    pod 'Nimble-Snapshots'# , '~> 6.3.0'
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = "YES"
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
        end
    end
end
